homeassistant:
  name: Thuis
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  elevation: !secret HOME_ELAVATION
  unit_system: metric
  time_zone: !secret HOME_TIME_ZONE
  customize: !include_dir_merge_named configuration/customizations

frontend:
http:
  api_password: !secret HTTP_PASSWORD

# Platforms
light: !include configuration/platforms/lights.yaml
climate: !include configuration/platforms/climate.yaml
media_player: !include configuration/platforms/media_players.yaml
device_tracker: !include configuration/platforms/device_trackers.yaml

# Components
nest: !include configuration/components/nest.yaml
zwave: !include configuration/components/zwave.yaml
rfxtrx: !include configuration/components/rfxtrx.yaml
mqtt: !include configuration/components/cloudmqtt.yaml
logger:
history:
discovery:
sun:
conversation:
logbook:
recorder:
  purge_days: 2
updater:

# Groups
group: !include_dir_named configuration/groups

# Zones
zone: !include configuration/zones/zones.yaml

sensor:
  platform: rfxtrx
  automatic_add: True

switch:
  platform: rfxtrx
  automatic_add: True
